-- CutoffData.lua
-- Auto-generated by update_cutoffs.py – do not edit manually.
-- Last updated : 2026-04-18 08:53 UTC
-- Season       : season-mn-1
-- Season end   : September 1, 2026

KeystoneCutoffsData = {
    seasonEnd = "September 1, 2026",
    updatedAt = "2026-04-18 08:53 UTC",
    season    = "season-mn-1",
    regions   = {
        ['eu'] = {
            percentiles = {
                ['p999'] = {
                    all      = { score = 3659.78, population = 924983, percentile = 0.100 },
                    horde    = { score = 3610.49, population = 486402, percentile = 0.100 },
                    alliance = { score = 3692.58, population = 438581, percentile = 0.100 },
                },
                ['p990'] = {
                    all      = { score = 3449.26, population = 924983, percentile = 1.000 },
                    horde    = { score = 3412.55, population = 486402, percentile = 1.000 },
                    alliance = { score = 3495.26, population = 438581, percentile = 1.000 },
                },
                ['p900'] = {
                    all      = { score = 3065.54, population = 924983, percentile = 10.000 },
                    horde    = { score = 3043.01, population = 486402, percentile = 10.001 },
                    alliance = { score = 3092.85, population = 438581, percentile = 10.001 },
                },
                ['p750'] = {
                    all      = { score = 2765.07, population = 924983, percentile = 25.000 },
                    horde    = { score = 2748.94, population = 486402, percentile = 25.001 },
                    alliance = { score = 2785.09, population = 438581, percentile = 25.000 },
                },
                ['p600'] = {
                    all      = { score = 2599.43, population = 924983, percentile = 40.001 },
                    horde    = { score = 2586.37, population = 486402, percentile = 40.000 },
                    alliance = { score = 2612.44, population = 438581, percentile = 40.000 },
                },
            },
            titles = {
                ['keystoneMyth'] = {
                    fixedScore = 3400,
                    all        = { score = 3391.69, population = 924983, percentile = 1.700 },
                    horde      = { score = 3389, population = 486402, percentile = 1.200 },
                    alliance   = { score = 3398.13, population = 438581, percentile = 2.201 },
                },
                ['keystoneLegend'] = {
                    fixedScore = 3000,
                    all        = { score = 2998.95, population = 924983, percentile = 14.900 },
                    horde      = { score = 2998.90, population = 486402, percentile = 13.800 },
                    alliance   = { score = 2999.58, population = 438581, percentile = 16.100 },
                },
                ['keystoneHero'] = {
                    fixedScore = 2500,
                    all        = { score = 2498.57, population = 924983, percentile = 44.500 },
                    horde      = { score = 2499.67, population = 486402, percentile = 43.900 },
                    alliance   = { score = 2499.35, population = 438581, percentile = 45.100 },
                },
                ['keystoneMaster'] = {
                    fixedScore = 2000,
                    all        = { score = 1999.92, population = 924983, percentile = 59.400 },
                    horde      = { score = 1998.10, population = 486402, percentile = 59.300 },
                    alliance   = { score = 1998.39, population = 438581, percentile = 59.600 },
                },
                ['keystoneConqueror'] = {
                    fixedScore = 1500,
                    all        = { score = 1499.44, population = 924983, percentile = 68.000 },
                    horde      = { score = 1496.30, population = 486402, percentile = 68.000 },
                    alliance   = { score = 1497.09, population = 438581, percentile = 68.100 },
                },
                ['keystoneExplorer'] = {
                    fixedScore = 1000,
                    all        = { score = 999.18, population = 924983, percentile = 76.800 },
                    horde      = { score = 999.02, population = 486402, percentile = 76.800 },
                    alliance   = { score = 999.38, population = 438581, percentile = 76.800 },
                },
            },
            updatedAt = "Sat Apr 18 2026 07:41:13 GMT+0000 (Coordinated Universal Time)",
        },
        ['us'] = {
            percentiles = {
                ['p999'] = {
                    all      = { score = 3638.69, population = 668745, percentile = 0.100 },
                    horde    = { score = 3552, population = 334162, percentile = 0.100 },
                    alliance = { score = 3673.62, population = 334583, percentile = 0.100 },
                },
                ['p990'] = {
                    all      = { score = 3401.59, population = 668745, percentile = 1.000 },
                    horde    = { score = 3329.57, population = 334162, percentile = 1.000 },
                    alliance = { score = 3442.30, population = 334583, percentile = 1.000 },
                },
                ['p900'] = {
                    all      = { score = 3015.54, population = 668745, percentile = 10.000 },
                    horde    = { score = 3002.94, population = 334162, percentile = 10.001 },
                    alliance = { score = 3034.32, population = 334583, percentile = 10.001 },
                },
                ['p750'] = {
                    all      = { score = 2699.90, population = 668745, percentile = 25.001 },
                    horde    = { score = 2681.71, population = 334162, percentile = 25.000 },
                    alliance = { score = 2720.39, population = 334583, percentile = 25.000 },
                },
                ['p600'] = {
                    all      = { score = 2471.02, population = 668745, percentile = 40.000 },
                    horde    = { score = 2436.28, population = 334162, percentile = 40.000 },
                    alliance = { score = 2506.43, population = 334583, percentile = 40.000 },
                },
            },
            titles = {
                ['keystoneMyth'] = {
                    fixedScore = 3400,
                    all        = { score = 3386.73, population = 668745, percentile = 1.100 },
                    horde      = { score = 3390.27, population = 334162, percentile = 0.600 },
                    alliance   = { score = 3395.59, population = 334583, percentile = 1.500 },
                },
                ['keystoneLegend'] = {
                    fixedScore = 3000,
                    all        = { score = 2999.75, population = 668745, percentile = 11.601 },
                    horde      = { score = 2999.68, population = 334162, percentile = 10.301 },
                    alliance   = { score = 2999.78, population = 334583, percentile = 12.901 },
                },
                ['keystoneHero'] = {
                    fixedScore = 2500,
                    all        = { score = 2497.32, population = 668745, percentile = 39.100 },
                    horde      = { score = 2499.34, population = 334162, percentile = 37.800 },
                    alliance   = { score = 2497.87, population = 334583, percentile = 40.300 },
                },
                ['keystoneMaster'] = {
                    fixedScore = 2000,
                    all        = { score = 1999.19, population = 668745, percentile = 54.500 },
                    horde      = { score = 1998.02, population = 334162, percentile = 53.700 },
                    alliance   = { score = 1999.95, population = 334583, percentile = 55.300 },
                },
                ['keystoneConqueror'] = {
                    fixedScore = 1500,
                    all        = { score = 1494.99, population = 668745, percentile = 63.500 },
                    horde      = { score = 1494.78, population = 334162, percentile = 62.900 },
                    alliance   = { score = 1495.13, population = 334583, percentile = 64.100 },
                },
                ['keystoneExplorer'] = {
                    fixedScore = 1000,
                    all        = { score = 997.80, population = 668745, percentile = 73.100 },
                    horde      = { score = 997.42, population = 334162, percentile = 72.700 },
                    alliance   = { score = 998.12, population = 334583, percentile = 73.500 },
                },
            },
            updatedAt = "Sat Apr 18 2026 07:41:13 GMT+0000 (Coordinated Universal Time)",
        },
        ['kr'] = {
            percentiles = {
                ['p999'] = {
                    all      = { score = 3526.48, population = 65078, percentile = 0.101 },
                    horde    = { score = 3500.50, population = 39148, percentile = 0.102 },
                    alliance = { score = 3566.32, population = 25930, percentile = 0.100 },
                },
                ['p990'] = {
                    all      = { score = 3321.54, population = 65078, percentile = 1.000 },
                    horde    = { score = 3270.77, population = 39148, percentile = 1.001 },
                    alliance = { score = 3376.11, population = 25930, percentile = 1.003 },
                },
                ['p900'] = {
                    all      = { score = 2936.43, population = 65078, percentile = 10.000 },
                    horde    = { score = 2901.59, population = 39148, percentile = 10.001 },
                    alliance = { score = 2984.02, population = 25930, percentile = 10.000 },
                },
                ['p750'] = {
                    all      = { score = 2701.20, population = 65078, percentile = 25.001 },
                    horde    = { score = 2692.27, population = 39148, percentile = 25.000 },
                    alliance = { score = 2717.36, population = 25930, percentile = 25.002 },
                },
                ['p600'] = {
                    all      = { score = 2601.75, population = 65078, percentile = 40.001 },
                    horde    = { score = 2598.15, population = 39148, percentile = 40.002 },
                    alliance = { score = 2606.18, population = 25930, percentile = 40.000 },
                },
            },
            titles = {
                ['keystoneMyth'] = {
                    fixedScore = 3400,
                    all        = { score = 3398.53, population = 65078, percentile = 0.501 },
                    horde      = { score = 3393.04, population = 39148, percentile = 0.301 },
                    alliance   = { score = 3389.62, population = 25930, percentile = 0.902 },
                },
                ['keystoneLegend'] = {
                    fixedScore = 3000,
                    all        = { score = 2998.37, population = 65078, percentile = 7.803 },
                    horde      = { score = 2997.03, population = 39148, percentile = 6.802 },
                    alliance   = { score = 2999.96, population = 25930, percentile = 9.302 },
                },
                ['keystoneHero'] = {
                    fixedScore = 2500,
                    all        = { score = 2499.69, population = 65078, percentile = 45.201 },
                    horde      = { score = 2498.20, population = 39148, percentile = 45.101 },
                    alliance   = { score = 2497.60, population = 25930, percentile = 45.503 },
                },
                ['keystoneMaster'] = {
                    fixedScore = 2000,
                    all        = { score = 1999.24, population = 65078, percentile = 60.701 },
                    horde      = { score = 1999.50, population = 39148, percentile = 60.700 },
                    alliance   = { score = 1999.24, population = 25930, percentile = 60.702 },
                },
                ['keystoneConqueror'] = {
                    fixedScore = 1500,
                    all        = { score = 1495.46, population = 65078, percentile = 69.701 },
                    horde      = { score = 1499.69, population = 39148, percentile = 69.603 },
                    alliance   = { score = 1498.24, population = 25930, percentile = 69.703 },
                },
                ['keystoneExplorer'] = {
                    fixedScore = 1000,
                    all        = { score = 997.83, population = 65078, percentile = 78.601 },
                    horde      = { score = 998.01, population = 39148, percentile = 78.402 },
                    alliance   = { score = 999.91, population = 25930, percentile = 78.801 },
                },
            },
            updatedAt = "Sat Apr 18 2026 07:41:13 GMT+0000 (Coordinated Universal Time)",
        },
        ['tw'] = {
            percentiles = {
                ['p999'] = {
                    all      = { score = 3588.55, population = 24547, percentile = 0.106 },
                    horde    = { score = 3536.73, population = 11644, percentile = 0.103 },
                    alliance = { score = 3653.88, population = 12903, percentile = 0.101 },
                },
                ['p990'] = {
                    all      = { score = 3422.48, population = 24547, percentile = 1.002 },
                    horde    = { score = 3371.56, population = 11644, percentile = 1.005 },
                    alliance = { score = 3454.56, population = 12903, percentile = 1.008 },
                },
                ['p900'] = {
                    all      = { score = 3065.78, population = 24547, percentile = 10.001 },
                    horde    = { score = 3046.51, population = 11644, percentile = 10.005 },
                    alliance = { score = 3086.27, population = 12903, percentile = 10.005 },
                },
                ['p750'] = {
                    all      = { score = 2806.40, population = 24547, percentile = 25.001 },
                    horde    = { score = 2785.98, population = 11644, percentile = 25.000 },
                    alliance = { score = 2824.31, population = 12903, percentile = 25.002 },
                },
                ['p600'] = {
                    all      = { score = 2647.90, population = 24547, percentile = 40.001 },
                    horde    = { score = 2641.67, population = 11644, percentile = 40.012 },
                    alliance = { score = 2653.47, population = 12903, percentile = 40.006 },
                },
            },
            titles = {
                ['keystoneMyth'] = {
                    fixedScore = 3400,
                    all        = { score = 3392.85, population = 24547, percentile = 1.304 },
                    horde      = { score = 3382.82, population = 11644, percentile = 0.902 },
                    alliance   = { score = 3393.93, population = 12903, percentile = 1.705 },
                },
                ['keystoneLegend'] = {
                    fixedScore = 3000,
                    all        = { score = 2999.70, population = 24547, percentile = 14.902 },
                    horde      = { score = 2998.11, population = 11644, percentile = 13.801 },
                    alliance   = { score = 2998.88, population = 12903, percentile = 16.004 },
                },
                ['keystoneHero'] = {
                    fixedScore = 2500,
                    all        = { score = 2497.62, population = 24547, percentile = 49.603 },
                    horde      = { score = 2497.83, population = 11644, percentile = 49.004 },
                    alliance   = { score = 2498.20, population = 12903, percentile = 50.105 },
                },
                ['keystoneMaster'] = {
                    fixedScore = 2000,
                    all        = { score = 1998.55, population = 24547, percentile = 63.201 },
                    horde      = { score = 1995.77, population = 11644, percentile = 62.607 },
                    alliance   = { score = 1998.38, population = 12903, percentile = 63.807 },
                },
                ['keystoneConqueror'] = {
                    fixedScore = 1500,
                    all        = { score = 1493.78, population = 24547, percentile = 71.202 },
                    horde      = { score = 1492.46, population = 11644, percentile = 70.903 },
                    alliance   = { score = 1499.37, population = 12903, percentile = 71.402 },
                },
                ['keystoneExplorer'] = {
                    fixedScore = 1000,
                    all        = { score = 998.67, population = 24547, percentile = 79.700 },
                    horde      = { score = 997.08, population = 11644, percentile = 79.406 },
                    alliance   = { score = 998.67, population = 12903, percentile = 80.005 },
                },
            },
            updatedAt = "Sat Apr 18 2026 07:41:13 GMT+0000 (Coordinated Universal Time)",
        },
    },
    scoreColors = {
    },
}
