-- CutoffData.lua
-- Auto-generated by update_cutoffs.py – do not edit manually.
-- Last updated : 2026-04-16 15:59 UTC
-- Season       : season-mn-1
-- Season end   : September 1, 2026

KeystoneCutoffsData = {
    seasonEnd = "September 1, 2026",
    updatedAt = "2026-04-16 15:59 UTC",
    season    = "season-mn-1",
    regions   = {
        ['eu'] = {
            percentiles = {
                ['p999'] = {
                    all      = { score = 3642.39, population = 906296, percentile = 0.100 },
                    horde    = { score = 3577.73, population = 476744, percentile = 0.100 },
                    alliance = { score = 3664.98, population = 429552, percentile = 0.100 },
                },
                ['p990'] = {
                    all      = { score = 3426.74, population = 906296, percentile = 1.000 },
                    horde    = { score = 3377.15, population = 476744, percentile = 1.000 },
                    alliance = { score = 3463.51, population = 429552, percentile = 1.000 },
                },
                ['p900'] = {
                    all      = { score = 3040.49, population = 906296, percentile = 10.000 },
                    horde    = { score = 3023.25, population = 476744, percentile = 10.000 },
                    alliance = { score = 3066.01, population = 429552, percentile = 10.000 },
                },
                ['p750'] = {
                    all      = { score = 2738, population = 906296, percentile = 25.001 },
                    horde    = { score = 2723.36, population = 476744, percentile = 25.000 },
                    alliance = { score = 2756.62, population = 429552, percentile = 25.000 },
                },
                ['p600'] = {
                    all      = { score = 2574.32, population = 906296, percentile = 40.000 },
                    horde    = { score = 2560.21, population = 476744, percentile = 40.000 },
                    alliance = { score = 2590.11, population = 429552, percentile = 40.000 },
                },
            },
            titles = {
                ['keystoneMyth'] = {
                    fixedScore = 3400,
                    all        = { score = 3397.80, population = 906296, percentile = 1.300 },
                    horde      = { score = 3391.05, population = 476744, percentile = 0.900 },
                    alliance   = { score = 3396.98, population = 429552, percentile = 1.800 },
                },
                ['keystoneLegend'] = {
                    fixedScore = 3000,
                    all        = { score = 2998.47, population = 906296, percentile = 13.500 },
                    horde      = { score = 2998.55, population = 476744, percentile = 12.400 },
                    alliance   = { score = 2999.07, population = 429552, percentile = 14.700 },
                },
                ['keystoneHero'] = {
                    fixedScore = 2500,
                    all        = { score = 2497.34, population = 906296, percentile = 43.300 },
                    horde      = { score = 2497.66, population = 476744, percentile = 42.700 },
                    alliance   = { score = 2498.67, population = 429552, percentile = 43.900 },
                },
                ['keystoneMaster'] = {
                    fixedScore = 2000,
                    all        = { score = 1999.23, population = 906296, percentile = 58.500 },
                    horde      = { score = 1997.01, population = 476744, percentile = 58.400 },
                    alliance   = { score = 1998.06, population = 429552, percentile = 58.701 },
                },
                ['keystoneConqueror'] = {
                    fixedScore = 1500,
                    all        = { score = 1495.63, population = 906296, percentile = 67.300 },
                    horde      = { score = 1496.43, population = 476744, percentile = 67.200 },
                    alliance   = { score = 1495.42, population = 429552, percentile = 67.400 },
                },
                ['keystoneExplorer'] = {
                    fixedScore = 1000,
                    all        = { score = 997.93, population = 906296, percentile = 76.300 },
                    horde      = { score = 997.41, population = 476744, percentile = 76.300 },
                    alliance   = { score = 998.33, population = 429552, percentile = 76.300 },
                },
            },
            updatedAt = "Thu Apr 16 2026 13:33:53 GMT+0000 (Coordinated Universal Time)",
        },
        ['us'] = {
            percentiles = {
                ['p999'] = {
                    all      = { score = 3608.42, population = 654769, percentile = 0.100 },
                    horde    = { score = 3535.42, population = 326946, percentile = 0.100 },
                    alliance = { score = 3654.01, population = 327823, percentile = 0.100 },
                },
                ['p990'] = {
                    all      = { score = 3367.78, population = 654769, percentile = 1.000 },
                    horde    = { score = 3306.94, population = 326946, percentile = 1.000 },
                    alliance = { score = 3421.71, population = 327823, percentile = 1.000 },
                },
                ['p900'] = {
                    all      = { score = 3004.97, population = 654769, percentile = 10.000 },
                    horde    = { score = 2969.96, population = 326946, percentile = 10.000 },
                    alliance = { score = 3018.69, population = 327823, percentile = 10.001 },
                },
                ['p750'] = {
                    all      = { score = 2682.79, population = 654769, percentile = 25.001 },
                    horde    = { score = 2667.56, population = 326946, percentile = 25.000 },
                    alliance = { score = 2700.53, population = 327823, percentile = 25.001 },
                },
                ['p600'] = {
                    all      = { score = 2436.88, population = 654769, percentile = 40.000 },
                    horde    = { score = 2402.23, population = 326946, percentile = 40.000 },
                    alliance = { score = 2472.12, population = 327823, percentile = 40.000 },
                },
            },
            titles = {
                ['keystoneMyth'] = {
                    fixedScore = 3400,
                    all        = { score = 3399.95, population = 654769, percentile = 0.800 },
                    horde      = { score = 3381.26, population = 326946, percentile = 0.500 },
                    alliance   = { score = 3397.10, population = 327823, percentile = 1.200 },
                },
                ['keystoneLegend'] = {
                    fixedScore = 3000,
                    all        = { score = 2998.88, population = 654769, percentile = 10.500 },
                    horde      = { score = 2999.68, population = 326946, percentile = 9.201 },
                    alliance   = { score = 2997.72, population = 327823, percentile = 11.800 },
                },
                ['keystoneHero'] = {
                    fixedScore = 2500,
                    all        = { score = 2498.52, population = 654769, percentile = 37.900 },
                    horde      = { score = 2497.88, population = 326946, percentile = 36.701 },
                    alliance   = { score = 2499.24, population = 327823, percentile = 39.100 },
                },
                ['keystoneMaster'] = {
                    fixedScore = 2000,
                    all        = { score = 1998.15, population = 654769, percentile = 53.700 },
                    horde      = { score = 1997.53, population = 326946, percentile = 52.900 },
                    alliance   = { score = 1998.57, population = 327823, percentile = 54.500 },
                },
                ['keystoneConqueror'] = {
                    fixedScore = 1500,
                    all        = { score = 1499.67, population = 654769, percentile = 62.700 },
                    horde      = { score = 1499.47, population = 326946, percentile = 62.100 },
                    alliance   = { score = 1499.69, population = 327823, percentile = 63.300 },
                },
                ['keystoneExplorer'] = {
                    fixedScore = 1000,
                    all        = { score = 996.78, population = 654769, percentile = 72.600 },
                    horde      = { score = 997.20, population = 326946, percentile = 72.200 },
                    alliance   = { score = 999.82, population = 327823, percentile = 72.900 },
                },
            },
            updatedAt = "Thu Apr 16 2026 13:33:53 GMT+0000 (Coordinated Universal Time)",
        },
        ['kr'] = {
            percentiles = {
                ['p999'] = {
                    all      = { score = 3503.18, population = 64167, percentile = 0.101 },
                    horde    = { score = 3467.34, population = 38617, percentile = 0.101 },
                    alliance = { score = 3537.52, population = 25550, percentile = 0.102 },
                },
                ['p990'] = {
                    all      = { score = 3290.73, population = 64167, percentile = 1.001 },
                    horde    = { score = 3236, population = 38617, percentile = 1.002 },
                    alliance = { score = 3344.02, population = 25550, percentile = 1.002 },
                },
                ['p900'] = {
                    all      = { score = 2880.38, population = 64167, percentile = 10.000 },
                    horde    = { score = 2850.16, population = 38617, percentile = 10.001 },
                    alliance = { score = 2936.68, population = 25550, percentile = 10.000 },
                },
                ['p750'] = {
                    all      = { score = 2679.21, population = 64167, percentile = 25.000 },
                    horde    = { score = 2672.62, population = 38617, percentile = 25.002 },
                    alliance = { score = 2691.37, population = 25550, percentile = 25.002 },
                },
                ['p600'] = {
                    all      = { score = 2569.48, population = 64167, percentile = 40.000 },
                    horde    = { score = 2567.39, population = 38617, percentile = 40.001 },
                    alliance = { score = 2573.95, population = 25550, percentile = 40.000 },
                },
            },
            titles = {
                ['keystoneMyth'] = {
                    fixedScore = 3400,
                    all        = { score = 3391.19, population = 64167, percentile = 0.401 },
                    horde      = { score = 3356.57, population = 38617, percentile = 0.300 },
                    alliance   = { score = 3386.79, population = 25550, percentile = 0.708 },
                },
                ['keystoneLegend'] = {
                    fixedScore = 3000,
                    all        = { score = 2998.86, population = 64167, percentile = 6.400 },
                    horde      = { score = 2998.26, population = 38617, percentile = 5.402 },
                    alliance   = { score = 2996.47, population = 25550, percentile = 8.000 },
                },
                ['keystoneHero'] = {
                    fixedScore = 2500,
                    all        = { score = 2499.12, population = 64167, percentile = 43.401 },
                    horde      = { score = 2498.82, population = 38617, percentile = 43.302 },
                    alliance   = { score = 2498.14, population = 25550, percentile = 43.601 },
                },
                ['keystoneMaster'] = {
                    fixedScore = 2000,
                    all        = { score = 1999.67, population = 64167, percentile = 59.302 },
                    horde      = { score = 1996.16, population = 38617, percentile = 59.401 },
                    alliance   = { score = 1998.17, population = 25550, percentile = 59.303 },
                },
                ['keystoneConqueror'] = {
                    fixedScore = 1500,
                    all        = { score = 1495.22, population = 64167, percentile = 68.501 },
                    horde      = { score = 1497.73, population = 38617, percentile = 68.403 },
                    alliance   = { score = 1494.85, population = 25550, percentile = 68.603 },
                },
                ['keystoneExplorer'] = {
                    fixedScore = 1000,
                    all        = { score = 999.30, population = 64167, percentile = 77.700 },
                    horde      = { score = 998.82, population = 38617, percentile = 77.502 },
                    alliance   = { score = 998.06, population = 25550, percentile = 78.102 },
                },
            },
            updatedAt = "Thu Apr 16 2026 13:33:53 GMT+0000 (Coordinated Universal Time)",
        },
        ['tw'] = {
            percentiles = {
                ['p999'] = {
                    all      = { score = 3574.56, population = 24278, percentile = 0.103 },
                    horde    = { score = 3522.03, population = 11529, percentile = 0.104 },
                    alliance = { score = 3605.20, population = 12749, percentile = 0.102 },
                },
                ['p990'] = {
                    all      = { score = 3395.85, population = 24278, percentile = 1.001 },
                    horde    = { score = 3343.98, population = 11529, percentile = 1.015 },
                    alliance = { score = 3428.27, population = 12749, percentile = 1.004 },
                },
                ['p900'] = {
                    all      = { score = 3031.24, population = 24278, percentile = 10.001 },
                    horde    = { score = 3015.42, population = 11529, percentile = 10.001 },
                    alliance = { score = 3050.71, population = 12749, percentile = 10.001 },
                },
                ['p750'] = {
                    all      = { score = 2766.35, population = 24278, percentile = 25.002 },
                    horde    = { score = 2749.11, population = 11529, percentile = 25.007 },
                    alliance = { score = 2783.34, population = 12749, percentile = 25.006 },
                },
                ['p600'] = {
                    all      = { score = 2626.91, population = 24278, percentile = 40.003 },
                    horde    = { score = 2620.90, population = 11529, percentile = 40.003 },
                    alliance = { score = 2631.77, population = 12749, percentile = 40.011 },
                },
            },
            titles = {
                ['keystoneMyth'] = {
                    fixedScore = 3400,
                    all        = { score = 3395.85, population = 24278, percentile = 1.001 },
                    horde      = { score = 3389.76, population = 11529, percentile = 0.607 },
                    alliance   = { score = 3395.85, population = 12749, percentile = 1.404 },
                },
                ['keystoneLegend'] = {
                    fixedScore = 3000,
                    all        = { score = 2999.70, population = 24278, percentile = 12.703 },
                    horde      = { score = 2999.61, population = 11529, percentile = 11.302 },
                    alliance   = { score = 2999.48, population = 12749, percentile = 14.001 },
                },
                ['keystoneHero'] = {
                    fixedScore = 2500,
                    all        = { score = 2499.01, population = 24278, percentile = 47.800 },
                    horde      = { score = 2497.51, population = 11529, percentile = 47.203 },
                    alliance   = { score = 2498.50, population = 12749, percentile = 48.404 },
                },
                ['keystoneMaster'] = {
                    fixedScore = 2000,
                    all        = { score = 1999.13, population = 24278, percentile = 61.702 },
                    horde      = { score = 1999.92, population = 11529, percentile = 61.107 },
                    alliance   = { score = 1994.75, population = 12749, percentile = 62.303 },
                },
                ['keystoneConqueror'] = {
                    fixedScore = 1500,
                    all        = { score = 1496.45, population = 24278, percentile = 70.101 },
                    horde      = { score = 1489.08, population = 11529, percentile = 69.807 },
                    alliance   = { score = 1492.03, population = 12749, percentile = 70.507 },
                },
                ['keystoneExplorer'] = {
                    fixedScore = 1000,
                    all        = { score = 995.40, population = 24278, percentile = 78.903 },
                    horde      = { score = 999.89, population = 11529, percentile = 78.203 },
                    alliance   = { score = 999.20, population = 12749, percentile = 79.402 },
                },
            },
            updatedAt = "Thu Apr 16 2026 13:33:53 GMT+0000 (Coordinated Universal Time)",
        },
    },
    scoreColors = {
        { score = 3940, color = "#FFD200" },
        { score = 3800, color = "#FF8A00" },
        { score = 3600, color = "#FF4F8F" },
        { score = 3400, color = "#CF38FF" },
        { score = 3200, color = "#5E7BFF" },
        { score = 3000, color = "#00C4FF" },
        { score = 2800, color = "#00E5C8" },
    },
}
